config/routes.rb
Rails.application.routes.draw do
  resources :user_profiles
  devise_for :users
  root to: 'home#index'
  get '/home', to: 'home#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable,
         :trackable, :omniauthable
  has_one :user_profile
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
  acts_as_taggable_on :tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def authenticate_admin!
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def show
  end

end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :set_user_profile, only: [:show, :edit, :update, :destroy]

  # GET /user_profiles
  # GET /user_profiles.json
  def index
    @user_profiles = UserProfile.all
  end

  # GET /user_profiles/1
  # GET /user_profiles/1.json
  def show
  end

  # GET /user_profiles/new
  def new
    @user_profile = UserProfile.new
  end

  # GET /user_profiles/1/edit
  def edit
    @user_profile = UserProfile.find(current_user.id)
  end

  # POST /user_profiles
  # POST /user_profiles.json
  def create
    @user_profile = UserProfile.new(user_profile_params)

    respond_to do |format|
      if @user_profile.save
        format.html { redirect_to @user_profile, notice: 'プロフィールの作成が完了しました。' }
        format.json { render :show, status: :created, location: @user_profile }
      else
        format.html { render :new }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_profiles/1
  # PATCH/PUT /user_profiles/1.json
  def update
    respond_to do |format|
      if @user_profile.update(user_profile_params)
        format.html { redirect_to @user_profile, notice: 'プロフィールのアップデートが完了しました。' }
        format.json { render :show, status: :ok, location: @user_profile }
      else
        format.html { render :edit }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_profiles/1
  # DELETE /user_profiles/1.json
  def destroy
    @user_profile.destroy
    respond_to do |format|
      format.html { redirect_to user_profiles_url, notice: 'User profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_profile
      @user_profile = UserProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_profile_params
      user_id = params.permit(:user_id)
      params.require(:user_profile).permit(:name, :birthday, :sex, :address, :introduce, :tag_list).
        merge(user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/home/index.html.erb
<h1>トップページです。</h1>

<% if user_signed_in? %>
  ログインしています。
<% else %>
  ログインしていません。
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TripExchange</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <nav>
        <div class="nav-wrapper">
          <a href='' class='brand-log'>Trip Exchange</a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <% if user_signed_in? %>
              <li><strong><%= link_to current_user.email, root_path %></strong></li>
              <li><%= link_to 'パスワード変更', edit_user_registration_path %></li>
              <li><%= link_to 'プロフィール作成(一時的に作成)', new_user_profile_path%></li>
              <li><%= link_to 'プロフィール変更', edit_user_profile_path(id: current_user.id) %></li>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'サインアップ', new_user_registration_path %></li>
              <li><%= link_to 'ログイン', new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>

 <%= yield %>
  </body>
</html>

app/views/user_profiles/_form.html.erb
<div class='container'>
  <%= form_with(model: user_profile, local: true) do |form| %>
    <% if user_profile.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user_profile.errors.count, "error") %> prohibited this user_profile from being saved:</h2>

        <ul>
        <% user_profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= hidden_field_tag :user_id, current_user.id %>

        <div class="field">
          <%= form.label :name, '名前' %>
          <%= form.text_field :name %>
        </div>

        <div class="field">
          <%= form.label :birthday, '誕生日' %>
          <%= form.date_select :birthday %>
        </div>

        <div class="field">
          <%= form.label :sex, '性別' %>
          <%= form.radio_button :sex, 'man' %>男性
          <%= form.radio_button :sex, 'woman' %>女性
          <%= form.radio_button :sex, 'unknown' %>不明
        </div>

        <div class="field">
          <%= form.label :address, '住んでいる都道府県' %>
          <%= form.text_field :address %>
        </div>

        <div class="field">
          <%= form.label :tag_list, '行ったことのある国' %>
          <%= form.text_field :tag_list, value: @user_profile.tag_list.join(','), class: "form-control" %>
        </div>

        <div class="field">
          <%= form.label :introduce, '自己紹介' %>
          <%= form.text_area :introduce %>
        </div>

        <div class="actions">
          <%= form.submit %>
        </div>
  <% end %>
</div>

app/views/user_profiles/edit.html.erb
<h2>プロフィール編集</h2>

<%= render 'form', user_profile: @user_profile %>

<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>プロフィール一覧</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Birthday</th>
      <th>Address</th>
      <th>Introduce</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_profiles.each do |user_profile| %>
      <tr>
        <td><%= user_profile.name %></td>
        <td><%= user_profile.birthday %></td>
        <td><%= user_profile.address %></td>
        <td><%= user_profile.introduce %></td>
        <td><%= link_to 'Show', user_profile %></td>
        <td><%= link_to 'Edit', edit_user_profile_path(user_profile) %></td>
        <td><%= link_to 'Destroy', user_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Profile', new_user_profile_path %>

app/views/user_profiles/new.html.erb
<h1>プロフィール登録</h1>

<%= render 'form', user_profile: @user_profile %>

<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>名前</strong>
  <%= @user_profile.name %>
</p>

<p>
  <strong>性別</strong>
  <%= @user_profile.sex %>
</p>

<p>
  <strong>誕生日</strong>
  <%= @user_profile.birthday %>
</p>

<p>
  <strong>お住いの都道府県</strong>
  <%= @user_profile.address %>
</p>

<p>
  <strong>自己紹介</strong>
  <%= @user_profile.introduce %>
</p>

<%= link_to 'Edit', edit_user_profile_path(@user_profile) %> |
<%= link_to 'Back', user_profiles_path %>